settings:
  logLevel: INFO
  commit:
    type:
      enabled: true
      required: true
      prompt:
        name: "select"
        options:
          page: 5
          force: false
    scope:
      enabled: true
      required: false
      prompt:
        name: "select"
        options:
          page: 5
          force: false
    description:
      enabled: true
      required: true
      prompt:
        name: "input"
        options:
          max: 75
          multiline: false
    body:
      enabled: true
      required: false
      prompt:
        name: "input"
        options:
          max: -1
          multiline: false
    footer:
      enabled: true
      required: false
      prompt:
        name: "input"
        options:
          max: -1
          multiline: false

# level must be 'type', 'scope', 'description', 'body', and 'footer'
commitMessage:
  values:
    - level: "type"
      key: "chore"
      text: "Chore"
      values:
        - level: "scope"
          key: "test"
          text: "Testing"
          values:
            - level: "description"
              key: "unittest"
              text: "Create new unit test"
    - level: "scope"
      key: "config"
      text: "Configuration"
      values:
        - level: "body"
          key: "create"
          text: "enable configuration for custom config"

version: 5
