# All **type** on each configuration can be 3 value only
#   1. list   -> in order to use this key the list.yaml must be presented and list of root name must be presented
#                the prompt will show as choice input
#   2. custom -> the prompt will show as string input
#   3. mix    -> this will mix between list and custom

# enable and require is configuration root level
# if enable is true, mean command will prompt user to input something
# and if require is true, you will cannot add empty string to that prompt

version: 4
settings:
  log: info
commit:
  key:
    type: list
    size: 15
  scope:
    type: mix
    size: 15
  message:
    type: mix
    size: 50
branch:
  iteration:
    enable: true
    require: true
  key:
    type: list
    size: 15
  title:
    type: mix
    size: 20
  description:
    enable: true
    require: false
