name: gitgo
description: git commit as formatting
since: '1, April 2018'
author:
  - name: Kamontat Chantrachirathumrong
    email: kamontat.c@hotmail.com
license: © 2018 Kamontat Chantrachirathumrong
versions:
  - tag: 1.4.0
    description: Add more commit list, and public release version
  - tag: 1.4.0-beta.4
    description: Fix setup config file error
  - tag: 1.4.0-beta.3
    description: Fix commit initial emoji error
  - tag: 1.4.0-beta.2
    description: Fix commit message lost
  - tag: 1.4.0-beta.1
    description: 'Release public version, Add BREAK_CHANGES'
  - tag: 1.4.0-alpha.1
    description: Change 'promptui => survey' library
  - tag: 1.3.0-beta.1
    description: 'Update ''commit release'', and update code during API changes'
  - tag: 1.3.0-alpha.2
    description: Fix pull error when specify branch and add missing options
  - tag: 1.3.0-alpha.1
    description: 'Add ''commit release'', and ''push deploy'' command'
  - tag: 1.2.0
    description: Update push algorithm and validator in commit
  - tag: 1.1.6
    description: Fix 'push' command
  - tag: 1.1.5
    description: Fix 'initial commit' not work
  - tag: 1.1.4
    description: Fix initial commit usage text
  - tag: 1.1.3
    description: Fix commit format error
  - tag: 1.1.2
    description: update colorize some output command
  - tag: 1.1.1
    description: 'Auto install, on first time'
  - tag: 1.1.0
    description: 'Completed, all neccessary basic for git command'
  - tag: 1.1.0-beta.2
    description: Fix command not throw 'config not found'
  - tag: 1.1.0-beta.1
    description: 'Able to open, get location, and get config settings'
  - tag: 1.0.0-beta.4
    description: Add 'get location' of config files
  - tag: 1.0.0-beta.3
    description: Update commit format
  - tag: 1.0.0-beta.2
    description: Add 'Status' features
  - tag: 1.0.0-beta.1
    description: Completed 'Commit' features
  - tag: 0.0.1-beta.1
    description: Completed 'Commit' as TEXT feature
  - tag: 0.0.1-alpha.7
    description: Completed 'pull' feature
  - tag: 0.0.1-alpha.6
    description: Completed push feature and improve usability
  - tag: 0.0.1-alpha.5
    description: Add 'Push-Set' command and improve help code
  - tag: 0.0.1-alpha.4
    description: Add 'Push' command
  - tag: 0.0.1-alpha.3
    description: Add 'Destroy' and helper flags/commands
  - tag: 0.0.1-alpha.2
    description: Add 'Init' and 'Add' commands
  - tag: 0.0.1-alpha.1
    description: Start project
