- name: Feature
  key:
    text: feature
    emoji:
      icon: ✨
      name: sparkles
  title: Add new features
- name: Improvement
  key:
    text: improvement
    emoji:
      icon: "\U0001F4C8"
      name: chart_with_upwards_trend
  title: Improvement
- name: Document
  key:
    text: document
    emoji:
      icon: "\U0001F4CB"
      name: clipboard
  title: Write some document
- name: Refactor
  key:
    text: refactor
    emoji:
      icon: "\U000026FD"
      name: fuelpump
  title: Refactor code
- name: Configuration
  key:
    text: configuration
    emoji:
      icon: "\U0001F527"
      name: wrench
  title: Update config
- name: Dependency
  key:
    text: dependency
    emoji:
      icon: "\U0001F4F1"
      name: mortar_board
  title: Update dependency
- name: Fix
  key:
    text: bug
    emoji:
      icon: "\U0001F48A"
      name: pill
  title: Fix something
- name: Logging
  key:
    text: log
    emoji:
      icon: "\U0001F4E0"
      name: fax
  title: Log
- name: Release
  key:
    text: release
    emoji:
      icon: "\U0001F393"
      name: mortar_board
  title: Release new version