config:
  commit:
    type: text # text | emoji
    emoji: string # string | emoji
    key:
      require: true # true | false 
    title:
      require: true # true | false 
      auto: false # true | false
      size: 50 # maximum charecter size
    message:
      require: false # true | false 
    showsize: 8 # list when show the 'commit list'
  editor: vim # $EDITOR | vim | nano | other cli..
