config:
    commit:
        type: text
        key:
            require: true
        title:
            require: true
            auto: true
            size: 50
        message:
            require: true
        showsize: 8
    editor: ''
