style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/gitgo
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - improve
        - perf
        - refactor
        - docs
  commit_groups:
    title_maps:
      feat: Features
      improve: Improving program
      perf: Improving performance
      refactor: Code Refactoring
      fix: Fixes Bug
      docs: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues: 
    prefix: 
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
