style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/gitgo
options:
  commits:
    filters:
      Type:
        - feat
        - improve
        - perf
        - fix
        - doc
        - test
  commit_groups:
    title_maps:
      feat: Feature
      improve: Improving application
      perf: Improving performance
      fix: Fixes Bug
      doc: Documentation
      test: Testing
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues: 
    prefix: 
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE